"""create users and deposits

Revision ID: 0a1edc14542b
Revises: 
Create Date: 2026-02-11 09:38:56.440952

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0a1edc14542b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
